// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pgstore

import (
	"time"

	"github.com/google/uuid"
)

type Bid struct {
	ID        uuid.UUID `db:"id" json:"id"`
	ProductID uuid.UUID `db:"product_id" json:"productId"`
	UserID    uuid.UUID `db:"user_id" json:"userId"`
	Amount    float64   `db:"amount" json:"amount"`
	CreatedAt time.Time `db:"created_at" json:"createdAt"`
}

type Product struct {
	ID           uuid.UUID `db:"id" json:"id"`
	SellerID     uuid.UUID `db:"seller_id" json:"sellerId"`
	Name         string    `db:"name" json:"name"`
	Description  string    `db:"description" json:"description"`
	BasePrice    float64   `db:"base_price" json:"basePrice"`
	AuctionEndAt time.Time `db:"auction_end_at" json:"auctionEndAt"`
	IsSold       bool      `db:"is_sold" json:"isSold"`
	CreatedAt    time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt    time.Time `db:"updated_at" json:"updatedAt"`
}

type Session struct {
	Token     string    `db:"token" json:"token"`
	Data      []byte    `db:"data" json:"data"`
	Expiry    time.Time `db:"expiry" json:"expiry"`
	CreatedAt time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt time.Time `db:"updated_at" json:"updatedAt"`
}

type User struct {
	ID           uuid.UUID `db:"id" json:"id"`
	UserName     string    `db:"user_name" json:"userName"`
	Email        string    `db:"email" json:"email"`
	PasswordHash []byte    `db:"password_hash" json:"passwordHash"`
	PasswordSalt []byte    `db:"password_salt" json:"passwordSalt"`
	Bio          string    `db:"bio" json:"bio"`
	CreatedAt    time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt    time.Time `db:"updated_at" json:"updatedAt"`
}
