// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package pgstore

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	Token     string             `db:"token" json:"token"`
	Data      []byte             `db:"data" json:"data"`
	Expiry    pgtype.Timestamptz `db:"expiry" json:"expiry"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type User struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	UserName     string             `db:"user_name" json:"userName"`
	Email        string             `db:"email" json:"email"`
	PasswordHash []byte             `db:"password_hash" json:"passwordHash"`
	PasswordSalt []byte             `db:"password_salt" json:"passwordSalt"`
	Bio          string             `db:"bio" json:"bio"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}
