// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users ("user_name", "email", "password_hash", "password_salt", "bio")
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateUserParams struct {
	UserName     string `db:"user_name" json:"userName"`
	Email        string `db:"email" json:"email"`
	PasswordHash []byte `db:"password_hash" json:"passwordHash"`
	PasswordSalt []byte `db:"password_salt" json:"passwordSalt"`
	Bio          string `db:"bio" json:"bio"`
}

// CreateUser
//
//	INSERT INTO users ("user_name", "email", "password_hash", "password_salt", "bio")
//	VALUES ($1, $2, $3, $4, $5)
//	RETURNING id
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserName,
		arg.Email,
		arg.PasswordHash,
		arg.PasswordSalt,
		arg.Bio,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
	id, user_name, password_hash, password_salt, email, bio, created_at, updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           uuid.UUID `db:"id" json:"id"`
	UserName     string    `db:"user_name" json:"userName"`
	PasswordHash []byte    `db:"password_hash" json:"passwordHash"`
	PasswordSalt []byte    `db:"password_salt" json:"passwordSalt"`
	Email        string    `db:"email" json:"email"`
	Bio          string    `db:"bio" json:"bio"`
	CreatedAt    time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt    time.Time `db:"updated_at" json:"updatedAt"`
}

// GetUserByEmail
//
//	SELECT
//		id, user_name, password_hash, password_salt, email, bio, created_at, updated_at
//	FROM users
//	WHERE email = $1
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.Email,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT
	id, user_name, password_hash, password_salt, email, bio, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIdRow struct {
	ID           uuid.UUID `db:"id" json:"id"`
	UserName     string    `db:"user_name" json:"userName"`
	PasswordHash []byte    `db:"password_hash" json:"passwordHash"`
	PasswordSalt []byte    `db:"password_salt" json:"passwordSalt"`
	Email        string    `db:"email" json:"email"`
	Bio          string    `db:"bio" json:"bio"`
	CreatedAt    time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt    time.Time `db:"updated_at" json:"updatedAt"`
}

// GetUserById
//
//	SELECT
//		id, user_name, password_hash, password_salt, email, bio, created_at, updated_at
//	FROM users
//	WHERE id = $1
func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.Email,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
